LineLength:
  Max: 120

Documentation:
  Enabled: False

WordArray:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: false

BlockLength:
  Max: 200

Gemspec/RequiredRubyVersion:
  Enabled: false
